stages:
  - lint
  - test
  - build

lint-clippy:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - make clippy

lint-format:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - make ci-lint

test-regular:
  stage: test
  image: jdrouet/docker-with-compose:20.10.8
  services:
    - docker:20.10.8-dind
  before_script:
    - docker info
  after_script:
    - docker-compose -f docker-compose.test.yml rm -sf
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml run runner

test-coverage:
  stage: test
  image: xd009642/tarpaulin
  # tarpaulin if broken for now
  allow_failure: true
  variables:
    RUST_LOG: info
    INBOX_HOSTNAME: smtp-server
    SMTP_HOSTNAME: smtp-server
    SMTP_PORT: 1025
    TEMPLATE_PROVIDER: local
    TEMPLATE_ROOT: ./template
  services:
    - name: reachfive/fake-smtp-server
      alias: smtp-server
  script:
    - make ci-coverage

test-integration:
  stage: test
  image: rust:1-buster
  variables:
    RUST_LOG: info
    INBOX_HOSTNAME: smtp-server
    SMTP_HOSTNAME: smtp-server
    SMTP_PORT: 1025
    TEMPLATE_PROVIDER: local
    TEMPLATE_ROOT: ./template
  services:
    - name: reachfive/fake-smtp-server
      alias: smtp-server
  script:
    - cargo build
    - cargo run &
    - sleep 5
    - sh script/integration.sh http://localhost:3000

build-alpine-canary:
  stage: build
  image: jdrouet/docker-with-buildx:20.10.8-0.6.3
  timeout: 2h
  only:
    - main
  services:
    - name: docker:20.10.8-dind
      command: ["--mtu=1300"]
  before_script:
    - docker buildx version
    - docker buildx create --name catapulte-build-alpine-canary --platform linux/amd64 --use
  after_script:
    - docker buildx rm catapulte-build-alpine-canary
  script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker buildx build --push --file multiarch-alpine.Dockerfile --platform linux/amd64 --tag jdrouet/catapulte:canary-alpine .

build-debian-canary:
  stage: build
  image: jdrouet/docker-with-buildx:20.10.8-0.6.3
  timeout: 3h
  only:
    - main
  services:
    - name: docker:20.10.8-dind
      command: ["--mtu=1300"]
  before_script:
    - docker buildx version
    - docker buildx create --name catapulte-build-debian-canary --platform linux/amd64 --use
  after_script:
    - docker buildx rm catapulte-build-debian-canary
  script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker buildx build --push --file multiarch.Dockerfile --platform linux/amd64 --tag jdrouet/catapulte:canary --tag jdrouet/catapulte:canary-debian .

