language: rust

rust: stable

env:
  global:
    - RUST_LOG=info
    - SMTP_HOSTNAME=localhost
    - SMTP_PORT=1025
    - TEMPLATE_PROVIDER=local
    - TEMPLATE_ROOT=./template

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: run rustfmt
      script:
        - make install-rustfmt
        - make ci-lint

    - stage: lint
      name: run clippy
      script:
        - make install-clippy
        - make clippy

    - stage: test
      name: run test
      rust: nightly
      script:
        - docker run -d -p 127.0.0.1:1025:1025 -p 127.0.0.1:1080:1080 reachfive/fake-smtp-server
        - make ci-test

    - stage: test
      name: run coverage
      script:
        - docker run -d -p 127.0.0.1:1025:1025 -p 127.0.0.1:1080:1080 reachfive/fake-smtp-server
        - make install-tarpaulin
        - make ci-coverage
