language: rust

rust: stable

cache: cargo

env:
  global:
    - RUST_LOG=info
    - SMTP_HOSTNAME=localhost
    - SMTP_PORT=1025
    - TEMPLATE_PROVIDER=local
    - TEMPLATE_ROOT=./template

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: run rustfmt
      script:
        - rustup component add rustfmt
        - make lint

    - stage: test
      name: run test
      rust: nightly
      script:
        - docker run -d -p 127.0.0.1:1025:1025 -p 127.0.0.1:1080:1080 reachfive/fake-smtp-server
        - make test

    - stage: test
      name: run coverage
      script:
        - docker run -d -p 127.0.0.1:1025:1025 -p 127.0.0.1:1080:1080 reachfive/fake-smtp-server
        - cargo install cargo-tarpaulin
        - cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash)
