[package]
name = "catapulte"
version = "1.0.0"
description = "Catapulte is an open source mailer you can host yourself. You can use it to quickly catapult your transactionnal emails to destination."
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
edition = "2021"
license-file = "license.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", features = ["multipart"] }
clap = { version = "4.0", features = ["derive", "env"] }
config = { version = "0.13", default-features = false }
handlebars = { version = "4.2" }
lettre = { default-features = false, features = [
  "builder",
  "pool",
  "rustls-tls",
  "smtp-transport",
  "tokio1-rustls-tls",
], version = "0.10.0-rc.6" }
mime = { version = "0.3" }
mrml = { version = "1.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tempfile = { version = "3.3" }
tokio = { version = "1.22", features = ["full"] }
tower-http = { version = "0.3", default-features = false, features = ["trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = { version = "2.4", features = ["axum_extras"] }
uuid = { version = "1.2", features = ["v4"] }

[dev-dependencies]
bytes = "^1.0"
common-multipart-rfc7578 = "0.6"
env-test-util = "1.0"
lazy_static = "1.4"
multer = "2.0"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
serial_test = "0.9"
wiremock = "0.5"
