[package]
name = "catapulte"
version = "0.1.0"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
env_logger = "0.7"
lettre = { features = ["connection-pool", "r2d2", "smtp-transport"], version = "0.9" }
log = "0.4"
r2d2 = "0.8"
url = "2.1"

[dev-dependencies]
actix-http = "1.0"
serial_test = "0.4"
