version = "v1"

[[metrics]]
name = "docker-image.size.alpine.amd64"
threshold = 5
expectation = "decrease"

[metrics.tags]
unit = "B"

[[metrics]]
name = "docker-image.size.debian.amd64"
threshold = 5
expectation = "decrease"

[metrics.tags]
unit = "B"
