version: "2"

services:
  smtp:
    image: reachfive/fake-smtp-server
    networks:
      - backend

  smtp-tls:
    image: namshi/smtp
    depends_on:
      - smtp
    environment:
      - CERTIFICATE_PATH=/selfsigned.crt
      - KEY_PATH=/selfsigned.key
      - PORT=1026
      - SMARTHOST_ADDRESS=smtp
      - SMARTHOST_PORT=1025
    networks:
      - backend
    volumes:
      - ./asset/selfsigned.key:/selfsigned.key:ro
      - ./asset/selfsigned.crt:/selfsigned.crt:ro

  runner:
    image: rust:buster
    command: ["cargo", "test"]
    working_dir: /code
    depends_on:
      - smtp
      - smtp-tls
    environment:
      - RUST_LOG=debug
      - TEST_INBOX_HOSTNAME=smtp
      - TEST_INBOX_PORT=1080
      - TEST_SMTP_HOSTNAME=smtp
      - TEST_SMTP_PORT=1025
      - TEST_SMTPS_HOSTNAME=smtp-tls
      - TEST_SMTPS_PORT=1026
      - TEMPLATE_ROOT=/code/template
    networks:
      - backend
    volumes:
      - ./:/code

networks:
  backend: {}
