version: "2"

services:
  smtp:
    image: reachfive/fake-smtp-server
    networks:
      - backend

  smtp-tls:
    build:
      context: .
      dockerfile: script/smtp-tls.Dockerfile
    depends_on:
      - smtp
    environment:
      - CERTIFICATE_PATH=/selfsigned.crt
      - KEY_PATH=/selfsigned.key
      - PORT=1026
      - SMARTHOST_ADDRESS=smtp
      - SMARTHOST_PORT=1025
    networks:
      - backend

  runner:
    build:
      context: .
      target: test
    depends_on:
      - smtp
      - smtp-tls
    environment:
      - RUST_LOG=debug
      - TEST_INBOX_HOSTNAME=smtp
      - TEST_INBOX_PORT=1080
      - TEST_SMTP_HOSTNAME=smtp
      - TEST_SMTP_PORT=1025
      - TEST_SMTPS_HOSTNAME=smtp-tls
      - TEST_SMTPS_PORT=1026
      - TEMPLATE_ROOT=/code/template
    networks:
      - backend

networks:
  backend: {}
