version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
      - image: reachfive/fake-smtp-server
    environment:
      TEMPLATE_ROOT: template
      SMTP_HOSTNAME: localhost
      SMTP_PORT: 1025
    steps:
      - run: cargo install tarpaulin
      - checkout
      - run: rustfmt --edition 2018 --check src/{**/,}*.rs
      - run: cargo tarpaulin --out Lcov --output-dir target --ciserver circle-ci --coveralls $CODECOV_TOKEN
      - run: bash <(curl -s https://codecov.io/bash) -f target/lcov.info
