version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - test

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
      - image: reachfive/fake-smtp-server
    environment:
      TEMPLATE_ROOT: template
      SMTP_HOSTNAME: localhost
      SMTP_PORT: 1025
    steps:
      - checkout
      - run: rustfmt --edition 2018 --check src/{**/,}*.rs
      - run: bash script/run-coverage.sh
      - run: bash script/push-coverage.sh

  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - run: docker buildx install
      - checkout
      - setup_remote_docker
      - run: docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker buildx build --platform linux/amd64,linux/386,linux/arm64 --tag jdrouet/catapulte:$CIRCLE_BRANCH --push .
