version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
      - image: reachfive/fake-smtp-server
    steps:
      - checkout
      - run: bash script/run-coverage.sh
      - run: bash script/push-coverage.sh
