version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
      - image: reachfive/fake-smtp-server
    environment:
      TEMPLATE_ROOT: template
      SMTP_HOSTNAME: localhost
      SMTP_PORT: 1025
    steps:
      - checkout
      - run: rustfmt --edition 2018 --check src/{**/,}*.rs
      - run: bash script/run-coverage.sh
      - run: bash script/push-coverage.sh
