on:
  push:
    branches:
      - "main"

jobs:
  build-alpine-canary:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push alpine canary
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./alpine.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-alpine

  build-debian-canary:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push debian canary
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:alpine,${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:debian-alpine
