on:
  push:
    branches:
      - "main"

jobs:
  build-alpine-canary:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}-build-alpine-canary
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push alpine canary
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./alpine.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-alpine

  build-debian-canary:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}-build-debian-canary
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push debian canary
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:debian,${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-debian
