on:
  workflow_call:
    inputs:
      version:
        description: 'Version of release'
        required: true
        default: 'testing'
      platforms:
        description: 'Platforms used to build'
        required: true
        default: 'linux/amd64,linux/arm64'
      publish:
        description: 'Pushed the docker image and publish the binary'
        required: true
        default: false

name: Build docker images

jobs:
  alpine:
    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.ref }}-build-docker-alpine-${{ inputs.version }}
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ inputs.platforms }}

      - name: build and push alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./alpine.Dockerfile
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ inputs.publish }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:${{ inputs.version }}-alpine

  debian:
    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.ref }}-build-docker-debian-${{ inputs.version }}
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ inputs.platforms }}

      - name: build and push debian
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.publish }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:${{ inputs.version }},${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:${{ inputs.version }}-debian
