on:
  push:
    tags:        
      - 'v*'

name: Release catapulte version

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: compute version
        id: version
        run: echo "version=$(echo ${GITHUB_REF} | cut -d 'v' -f 2)" >> $GITHUB_OUTPUT


  build-alpine:
    runs-on: ubuntu-latest
    needs: variables
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: build and push alpine canary
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:${{ needs.variables.outputs.version }}-alpine

  build-debian:
    runs-on: ubuntu-latest
    needs: variables
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push debian canary
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:${{ needs.variables.outputs.version }},${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:${{ needs.variables.outputs.version }}-debian
