on:
  push:
    branches:
      - "main"

jobs:
  build-alpine:
    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.ref }}-build-docker-alpine-canary
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: build and push alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./alpine.Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-alpine

      - name: publish image size metric
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-alpine
          IMAGE_SIZE=$(docker image inspect ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-alpine | jq .[0].Size)
          curl https://codebench.cloud/binaries/codebench-cli-amd64 -o ./codebench-cli
          chmod +x ./codebench-cli
          ./codebench-cli --token ${{ secrets.CODEBENCH_TOKEN }} publish docker-image.size.alpine.amd64 $IMAGE_SIZE

  build-debian:
    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.ref }}-build-docker-debian-canary
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: build and push debian
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: jdrouet/catapulte:canary,jdrouet/catapulte:canary-debian

      - name: publish image size metric
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-debian
          IMAGE_SIZE=$(docker image inspect ${{ secrets.DOCKER_HUB_USERNAME }}/catapulte:canary-debian | jq .[0].Size)
          curl https://ci-metrics.eu/binaries/cimetrics-cli-amd64 -o ./cimetrics-cli
          chmod +x ./cimetrics-cli
          ./cimetrics-cli --token ${{ secrets.CODEBENCH_TOKEN }} publish docker-image.size.debian.amd64 $IMAGE_SIZE
